const mongoose = require("mongoose");

const vehicleSchema = new mongoose.Schema(
  {
    type: { type: String, required: true },
    make: { type: String, required: true },
    model: { type: String, required: true },
    year: Number,
    registrationNumber: { type: String, required: true },
    fuel_type: { type: String },
    color: String,
    isActive: { type: Boolean, default: true },
    rc_number: String,
    fit_up_to: Date,
    registration_date: Date,
    owner_name: String,
    father_name: String,
    present_address: String,
    permanent_address: String,
    mobile_number: String,
    vehicle_category: String,
    vehicle_chasi_number: String,
    vehicle_engine_number: String,
    maker_description: String,
    maker_model: String,
    body_type: String,
    norms_type: String,
    financer: String,
    financed: Boolean,
    insurance_company: String,
    insurance_policy_number: String,
    insurance_upto: Date,
    manufacturing_date: Date,
    registered_at: String,
    tax_upto: Date,
    tax_paid_upto: String,
    cubic_capacity: Number,
    vehicle_gross_weight: Number,
    no_cylinders: Number,
    seat_capacity: Number,
    sleeper_capacity: Number,
    standing_capacity: Number,
    wheelbase: Number,
    unladen_weight: Number,
    vehicle_category_description: String,
    pucc_number: String,
    pucc_upto: Date,
    permit_number: String,
    permit_issue_date: Date,
    permit_valid_from: Date,
    permit_valid_upto: Date,
    permit_type: String,
    national_permit_number: String,
    national_permit_upto: Date,
    national_permit_issued_by: String,
    non_use_status: String,
    non_use_from: Date,
    non_use_to: Date,
    blacklist_status: String,
    noc_details: String,
    owner_number: Number,
    rc_status: String,
    masked_name: Boolean,
    challan_details: String,
    variant: String,
    rto_code: String,
  },
  { timestamps: true }
);

module.exports = mongoose.model("Vehicle", vehicleSchema);
